DESCRIPTION = "Opie Phase disguishes oneself through its' simple, clean and slick look. \
It is based on http://www.usermode.org/code.html Phase 0.4."
SECTION = "opie/styles"
LICENSE = "GPLv2"
# FIXME stopgap until split archives have license files included
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/GPL-2.0;md5=801f80980d171dd6425610833a22dbe6"
APPNAME = "phasestyle"

S = "${WORKDIR}/phase"

inherit opie
